name: Build

on: push

jobs:
  Build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ 3.5, 3.6, 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv --python 3
          pipenv sync --dev

      - name: Check code style
        run: |
          pipenv run flake8 hutils *.py
          pipenv run pytest
